### ISSUE TITLE
Failed to compile vertex shader LitVertexFetch on mobile

### ISSUE THREAD

**Issue by yushli** [MonkeyFirst/urho3d-component-explosion#1]
When I tried to run this sample on mobile, it reports:
:Failed to compile vertex shader LitVertexFetch(DIRLIGHT NORMALMAP PERPIXEL SHADOW):

Maybe the shader doesn't comply with GLES?

**Comment by MonkeyFirst** [comment]
maybe, because I tested it only on my laptop with Win 8.1 64x nvidia 640m (supports up to opengl 4.5)
this feature as i remember, required at last - opengl 3.1 (opengl 3 es) with supporting vertex fetch (fetching from texture in vetrex shader). So if your hardware do not support VTF you probably got an error\crash.
